{% set name = "openinference-instrumentation-openai" %}
{% set version = "0.1.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_openai-{{ version }}.tar.gz
  sha256: 970efaa8c82f9435dc2cf445536cc79776f6830819b7ae3530d284a0008b57ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.12
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.12
    - openinference-semantic-conventions >=0.1.9
    - typing-extensions
    - wrapt

test:
  requires:
    - python {{ python_min }}
  imports:
    - openinference.instrumentation.openai

about:
  summary: OpenInference OpenAI Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
